export default {
  id: 9755,
  video: {
    original: {
      url: 'https://videos.files.wordpress.com/HF3JEHI0/work-that-body.mp4',
    },
    width: 1920,
    height: 1080,
    videopress: {
      guid: 'HF3JEHI0',
      title: 'work-that-body-mp4',
      description: '',
      width: 1920,
      height: 1080,
      duration: 320704,
      display_embed: true,
      allow_download: false,
      rating: 'G',
      poster: 'https://videos.files.wordpress.com/HF3JEHI0/work-that-body_mp4_hd_1080p.original.jpg',
      original: 'https://videos.files.wordpress.com/HF3JEHI0/work-that-body.mp4',
      watermark: false,
      bg_color: false,
      files: {
        std: {
          mp4: 'work-that-body_mp4_std.mp4',
          original_img: 'work-that-body_mp4_std.original.jpg',
          thumbnail_img: 'work-that-body_mp4_std.thumbnail.jpg',
        },
        avc_240p: {
          mp4: 'work-that-body_mp4_avc_240p.mp4',
          original_img: 'work-that-body_mp4_avc_240p.original.jpg',
          thumbnail_img: 'work-that-body_mp4_avc_240p.thumbnail.jpg',
          hls: 'work-that-body_mp4_avc_240p.master.m3u8',
          dash: 'work-that-body_mp4_avc_240p.dash.mpd',
        },
        dvd: {
          mp4: 'work-that-body_mp4_dvd.mp4',
          original_img: 'work-that-body_mp4_dvd.original.jpg',
          thumbnail_img: 'work-that-body_mp4_dvd.thumbnail.jpg',
          hls: 'work-that-body_mp4_dvd.master.m3u8',
          dash: 'work-that-body_mp4_dvd.dash.mpd',
        },
        hd: {
          mp4: 'work-that-body_mp4_hd.mp4',
          original_img: 'work-that-body_mp4_hd.original.jpg',
          thumbnail_img: 'work-that-body_mp4_hd.thumbnail.jpg',
          hls: 'work-that-body_mp4_hd.master.m3u8',
          dash: 'work-that-body_mp4_hd.dash.mpd',
        },
        hd_1080p: {
          mp4: 'work-that-body_mp4_hd_1080p.mp4',
          original_img: 'work-that-body_mp4_hd_1080p.original.jpg',
          thumbnail_img: 'work-that-body_mp4_hd_1080p.thumbnail.jpg',
          hls: 'work-that-body_mp4_hd_1080p.master.m3u8',
          dash: 'work-that-body_mp4_hd_1080p.dash.mpd',
        },
      },
      file_url_base: {
        http: 'http://videos.videopress.com/HF3JEHI0/',
        https: 'https://videos.files.wordpress.com/HF3JEHI0/',
      },
      blog_id: 202592704,
      post_id: 9641,
      is_private: false,
      privacy_setting: 2,
      upload_date: '2022-07-05T18:20:11+0000',
      finished: true,
      files_status: {
        std: {
          mp4: 'DONE',
          ogg: 'DONE',
        },
        avc_240p: {
          mp4: 'DONE',
        },
        dvd: {
          mp4: 'DONE',
        },
        hd: {
          mp4: 'DONE',
        },
        hd_1080p: {
          mp4: 'DONE',
        },
        hd_1080p_compat: null,
        hevc_1440p: null,
        vp9_1440p: null,
        hevc_2160p: null,
        vp9_2160p: null,
      },
      subtitles: [],
      tracks: [],
      adaptive_streaming: 'https://videos.files.wordpress.com/HF3JEHI0/work-that-body_mp4.adaptive_4.m3u8',
      adaptive_streaming_r: null,
      format_meta: {
        std: {
          codec: 'avc',
          label: '224p',
          vertical_lines: 224,
        },
        avc_240p: {
          codec: 'avc',
          label: '240p',
          vertical_lines: 240,
        },
        dvd: {
          codec: 'avc',
          label: '480p',
          vertical_lines: 480,
        },
        hd: {
          codec: 'avc',
          label: '720p',
          vertical_lines: 720,
        },
        hd_1080p: {
          codec: 'avc',
          label: '1080p',
          vertical_lines: 1080,
        },
        hevc_1440p: {
          codec: 'hevc',
          label: '1440p',
          vertical_lines: 1440,
        },
        vp9_1440p: {
          codec: 'vp9',
          label: '1440p',
          vertical_lines: 1440,
        },
        hevc_2160p: {
          codec: 'hevc',
          label: '4K',
          vertical_lines: 2160,
        },
        vp9_2160p: {
          codec: 'vp9',
          label: '4K',
          vertical_lines: 2160,
        },
      },
      thumbnails_grid: {
        grid_interval: 1000,
        grid_width: 10,
        grid_height: 10,
        thumbs_height: 288,
        files: [
          {
            file: 'work-that-body_mp4.thumbgrid_0.jpg',
            start_time_ms: 0,
            end_time_ms: 100000,
            thumbs_count: 100,
          },
          {
            file: 'work-that-body_mp4.thumbgrid_1.jpg',
            start_time_ms: 100000,
            end_time_ms: 200000,
            thumbs_count: 100,
          },
          {
            file: 'work-that-body_mp4.thumbgrid_2.jpg',
            start_time_ms: 200000,
            end_time_ms: 300000,
            thumbs_count: 100,
          },
          {
            file: 'work-that-body_mp4.thumbgrid_3.jpg',
            start_time_ms: 300000,
            end_time_ms: 321000,
            thumbs_count: 21,
          },
        ],
      },
      thumbnail_generating: false,
    },
    file_statuses: {
      ogg: 'DONE',
      mp4: 'DONE',
      dvd: 'DONE',
      hd: 'DONE',
      hd_1080p: 'DONE',
    },
  },
  post_title: 'Work That Body!',
  m2l_cat: {
    term_id: 31,
    name: 'K-3',
    slug: 'k-3',
    term_group: 0,
    term_taxonomy_id: 31,
    taxonomy: 'm2l_category',
    description: '',
    parent: 0,
    count: 16,
    filter: 'raw',
    term_order: '2',
  },
  post_name: 'work-that-body',
  tags: [
    {
      term_id: 34,
      name: 'Physical Education',
      slug: 'physical-education',
      term_group: 0,
      term_taxonomy_id: 34,
      taxonomy: 'm2l_tag',
      description: '',
      parent: 0,
      count: 3,
      filter: 'raw',
      term_order: '0',
    },
  ],
  pos: {
    x: 836.65625,
    y: -45.75,
    width: 328.328125,
    height: 229.6796875,
    top: -45.75,
    right: 1164.984375,
    bottom: 183.9296875,
    left: 836.65625,
  },
  scroll: 891.5,
  viewportWidth: 1260,
};
